# Generated by Django 5.0.3 on 2024-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_prix_flat_price_flat_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
