# Generated by Django 5.0.3 on 2024-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Dish',
        ),
    ]
