# Generated by Django 5.0.3 on 2024-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_flat_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
